DROP TABLE IF EXISTS endpoint_hits;

CREATE TABLE IF NOT EXISTS endpoint_hits (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app             VARCHAR(255) NOT NULL,
    uri             VARCHAR(255) NOT NULL,
    ip              VARCHAR(15) NOT NULL,
    hit_timestamp   TIMESTAMP
);